ALTER TABLE TAG ALTER COLUMN TYPE SET DATA TYPE VARCHAR(191);
UPDATE TAG SET TYPE = 'CATEGORY' WHERE TYPE = '1';
UPDATE TAG SET TYPE = 'PERSON' WHERE TYPE = '2';
UPDATE TAG SET TYPE = 'ALBUM' WHERE TYPE = '3';

ALTER TABLE STORAGE ALTER COLUMN KEY RENAME TO STORAGE_KEY;

ALTER TABLE IMAGE ADD STORAGE_FILENAME VARCHAR(191) NULL;
UPDATE IMAGE SET STORAGE_FILENAME = CONCAT('00000000000', ID, '.', FILE_EXTENSION) WHERE ID > 0 AND ID < 10;
UPDATE IMAGE SET STORAGE_FILENAME = CONCAT('0000000000', ID, '.', FILE_EXTENSION) WHERE ID > 9 AND ID < 100;
UPDATE IMAGE SET STORAGE_FILENAME = CONCAT('000000000', ID, '.', FILE_EXTENSION) WHERE ID > 99 AND ID < 1000;
UPDATE IMAGE SET STORAGE_FILENAME = CONCAT('00000000', ID, '.', FILE_EXTENSION) WHERE ID > 999 AND ID < 10000;
UPDATE IMAGE SET STORAGE_FILENAME = CONCAT('0000000', ID, '.', FILE_EXTENSION) WHERE ID > 9999 AND ID < 100000;

ALTER TABLE IMAGE ADD NEW_TAG_STATUS VARCHAR(191) NULL;
UPDATE IMAGE SET NEW_TAG_STATUS = 'UNCHECKED';

ALTER TABLE IMAGE ALTER COLUMN THUMB_STATUS SET DATA TYPE VARCHAR(191);
UPDATE IMAGE SET THUMB_STATUS = 'GENERATION_ERROR' WHERE THUMB_STATUS = '-1';
UPDATE IMAGE SET THUMB_STATUS = 'NO_THUMB' WHERE THUMB_STATUS = '0';
UPDATE IMAGE SET THUMB_STATUS = 'THUMB_100_100' WHERE THUMB_STATUS = '1';

ALTER TABLE IMAGE ALTER COLUMN RESOLUTION_STATUS SET DATA TYPE VARCHAR(191);
UPDATE IMAGE SET RESOLUTION_STATUS = 'GENERATION_ERROR' WHERE RESOLUTION_STATUS = '-1';
UPDATE IMAGE SET RESOLUTION_STATUS = 'NO_RESOLUTION' WHERE RESOLUTION_STATUS = '0';
UPDATE IMAGE SET RESOLUTION_STATUS = 'GENERATION_SUCCESS' WHERE RESOLUTION_STATUS = '1';

ALTER TABLE IMAGE ALTER COLUMN CREATED_DATE RENAME TO CREATED_DATETIME;

SCRIPT TO 'dump.sql';
