#
# Spring Boot configuration
#  - options: https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
#

info:
  application:
    name: '@app.name.pretty@'
    version: '@project.version@'
    revision: '@buildNumber@'
    buildDate: '@timestamp@'
    vendor: '@organization.name@'

server:
  address: 127.0.0.1
  port: 8080
  error:
    whitelabel:
      enabled: false
    include-message: always

spring:

  jpa:
    # Open Session In View (see https://www.baeldung.com/spring-open-session-in-view)
    open-in-view: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:h2:mem:image-tags-db;MODE=MariaDB;DATABASE_TO_LOWER=TRUE
    username: image-tags_user
    password: image-tags_password
    # Connection Pooling (see https://github.com/brettwooldridge/HikariCP#configuration-knobs-baby)
    hikari:
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 2000000
      minimumIdle: 3
      maximumPoolSize: 5
      poolName: SpringBootHikariCP

  liquibase:
    change-log: classpath:/db/changelog/master.xml

  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /css/**, /images/**, /js/**

  jackson:
    default-property-inclusion: NON_NULL

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  main:
    allow-circular-references: true

logging:
  level:
    ROOT: WARN
    '[org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer]': INFO
    '[karstenroethig.imagetags.webapp.Application]': INFO
    '[karstenroethig.imagetags.webapp.config.SchedulingConfig]': INFO
    '[karstenroethig.imagetags.webapp.service.impl.ImageImportServiceImpl]': INFO
    '[karstenroethig.imagetags.webapp.service.impl.CleanupServiceImpl]': INFO
    '[karstenroethig.imagetags.webapp]': WARN
  file:
    name: log/image-tags.log


---

spring:

  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: false

  h2:
    console:
      enabled: true # accessible via http://localhost:8080/h2-console

  liquibase:
    change-log: classpath:/db/changelog/master-dev.xml

  thymeleaf:
    # Reload templates without restarting the container
    cache: false

server:
  # Server only listens to localhost
  address: 127.0.0.1

logging:
  level:
    ROOT: INFO
    '[karstenroethig.imagetags.webapp]': DEBUG
  file:
    name: target/log/image-tags.log

app:
  backup:
    backupDirectory: target/backups
