#
# Spring Boot configuration
#  - options:
#      - https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
#      - https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-docs/src/main/asciidoc/appendix-application-properties.adoc
#

server:
  port: 4080

spring:

  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    open-in-view: false

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:image-tags-db
    username: ImageTagsUser
    password: ImageTagsUser
    # Connection Pooling (see https://github.com/brettwooldridge/HikariCP#configuration-knobs-baby)
    hikari:
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 2000000
      minimumIdle: 3
      maximumPoolSize: 5
      poolName: SpringBootHikariCP

  resources:
    chain:
      cache: true
      html-application-cache: true
      strategy:
        content:
          enabled: true
          paths: /css/**, /images/**, /js/**

  liquibase:
    change-log: classpath:/db/changelog/master.xml
